### ISSUE TITLE
Migration Play 2.4

### ISSUE THREAD

**Issue by fredoche** [siz-io/siz-api#50]
Dans le cadre de la migration de l'appli vers play 2.4, plusieurs items sont à prévoir:
- [x] changement java 8 dans travis et dans docker.
- [x] changement du plugin reactive-mongo-play: le nouveau utilise l'injection, et le nom a changé.
- [x] Voir si cela donne plus de flexibilité pour résoudre les problèmes d'atente de mongo dans les tests.
- [x] Global.scala don't exist anymore
- [x] Refactoring filter for injection
- [x] Remove v1.0 API compatibility

**Comment by jdauphant** [comment]
To check : 
- [ ] A incorrect API path return a Json Error
- [ ] A bad request/Internal Server Error generated by a controller shouldn't have to be replaced by a generic message
- [X] DB index are created correctly

**Comment by jdauphant** [comment]
- [ ] newBoxToBox could be in the companion object instead of the DAO

**Comment by fredoche** [comment]
c'est good.
