### ISSUE TITLE
Find a way to have multiple trusted proxies

### ISSUE THREAD

**Issue by jdauphant** [siz-io/siz-api#68]
Using variables to configure proxy FORWARDED_TRUSTED_PROXIES permit only one subnet.

Solution : 
- Use multiple variable _1 _2 _3
- Find how to made a list from env variable in configuration
- Hard code docker subnet
- Accept all 0.0.0.0/0

**Comment by fredoche** [comment]
tocket ouvert chez play, pbm contourné chez nous 
https://github.com/playframework/playframework/issues/4906
